--- #YAML:1.0
name: Inline-Parrot
version: 0.13
author:
  - Flavio S. Glock, E<lt>fglock@cpan.orgE<gt>
abstract: Inline Parrot code in Perl5
license: perl
requires:
  Carp: 0
  File::Spec: 0
  IO::File: 0
  IPC::Open3: 0
  Inline: 0
provides:
  Inline::Parrot:
    file: lib/Inline/Parrot.pm
    version: 0.13
  Inline::Parrot::parrot:
    file: lib/Inline/Parrot/parrot.pm
generated_by: Module::Build version 0.25
