--- #YAML:1.0
name: Inline-Parrot
version: 0.12
author:
  - Flavio S. Glock, E<lt>fglock@cpan.orgE<gt>
abstract: Inline Parrot code in Perl5
license: perl
requires:
  Inline: 0
provides: {}
generated_by: Module::Build version 0.25
