# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Inline-Parrot
version:      0.11
version_from: lib/Inline/Parrot.pm
installdirs:  site
requires:
    Inline:                        0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
