--- #YAML:1.0
name: Inline-Parrot
version: 0.15
author:
  - Flavio S. Glock, E<lt>fglock@cpan.orgE<gt>
abstract: Inline Parrot code in Perl5
license: perl
requires:
  Carp: 0
  File::Spec: 0
  IO::File: 0
  IPC::Open3: 0
  Inline: 0
provides: {}
generated_by: Module::Build version 0.24
